version : '3'

services:
    database:
        image: postgres:10.8-alpine
        ports:
            - 5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=d3m0g0